window.EQUIPOS = [
  {
    "codigo": "XTM-JUMBO-133",
    "equipo": "JUMBO S1D BOOMER",
    "tipo": "Jumbo",
    "modelo": "Boomer S1D",
    "marca": "Epiroc",
    "estado": "Certificado",
    "tipo_certificado": "FOPS/ROPS",
    "rig": "8999795900",
    "serie": "TMG25URE0133",
    "certificado_pdf": "./certificados/XTM-JUMBO-133_BOOMER-S1D_FOPS-ROPS.pdf",
    "validacion": "./validar.html?id=XTM-JUMBO-133",
    "qr": "./qr/XTM-JUMBO-133.png"
  },
  {
    "codigo": "XTM-JUMBO-163",
    "equipo": "JUMBO SIMBA S7D",
    "tipo": "Jumbo",
    "modelo": "Simba S7D",
    "marca": "Epiroc",
    "estado": "Certificado",
    "tipo_certificado": "FOPS/ROPS",
    "rig": "8999797800",
    "serie": "TMG25URE0163",
    "certificado_pdf": "./certificados/XTM-JUMBO-163_SIMBA-S7D_FOPS-ROPS.pdf",
    "validacion": "./validar.html?id=XTM-JUMBO-163",
    "qr": "./qr/XTM-JUMBO-163.png"
  },
  {
    "codigo": "XTM-JUMBO-187",
    "equipo": "JUMBO S1D BOOMER",
    "tipo": "Jumbo",
    "modelo": "Boomer S1D",
    "marca": "Epiroc",
    "estado": "Pendiente",
    "tipo_certificado": "Sin certificado adjunto",
    "rig": "",
    "serie": "",
    "certificado_pdf": "",
    "validacion": "./validar.html?id=XTM-JUMBO-187",
    "qr": ""
  },
  {
    "codigo": "XTM-JUMBO-587",
    "equipo": "JUMBO DD311D",
    "tipo": "Jumbo",
    "modelo": "DD311D",
    "marca": "Sandvik",
    "estado": "Certificado",
    "tipo_certificado": "Cabina FOPS/ROPS",
    "rig": "L22D7587",
    "serie": "L22D7587",
    "certificado_pdf": "./certificados/XTM-JUMBO-587_DD311D_CERT-CABINA.pdf",
    "validacion": "./validar.html?id=XTM-JUMBO-587",
    "qr": "./qr/XTM-JUMBO-587.png"
  },
  {
    "codigo": "XTM-JUMBO-381",
    "equipo": "JUMBO BOLTEC",
    "tipo": "Jumbo",
    "modelo": "Boltec M",
    "marca": "Epiroc",
    "estado": "Certificado",
    "tipo_certificado": "Pack FOPS/ROPS + supresion + gases + A/C",
    "rig": "8999473200",
    "serie": "TMG20URE0381",
    "certificado_pdf": "./certificados/XTM-JUMBO-381_BOLTEC-M_CERTIFICADOS.pdf",
    "validacion": "./validar.html?id=XTM-JUMBO-381",
    "qr": "./qr/XTM-JUMBO-381.png"
  },
  {
    "codigo": "XTM-LHD-033",
    "equipo": "SCOOP ST1030",
    "tipo": "LHD",
    "modelo": "Scooptram ST1030",
    "marca": "Epiroc",
    "estado": "Certificado",
    "tipo_certificado": "FOPS/ROPS",
    "rig": "8997991900",
    "serie": "CNN25URE0033",
    "certificado_pdf": "./certificados/XTM-LHD-033_SCOOP-ST1030_FOPS-ROPS.pdf",
    "validacion": "./validar.html?id=XTM-LHD-033",
    "qr": "./qr/XTM-LHD-033.png"
  },
  {
    "codigo": "XTM-LHD-043",
    "equipo": "SCOOP ST1030",
    "tipo": "LHD",
    "modelo": "Scooptram ST1030",
    "marca": "Atlas Copco",
    "estado": "Certificado",
    "tipo_certificado": "ROPS/FOPS Test Certificate",
    "rig": "",
    "serie": "LHD043",
    "certificado_pdf": "./certificados/XTM-LHD-043_SCOOP-ST1030_FOPS-ROPS.pdf",
    "validacion": "./validar.html?id=XTM-LHD-043",
    "qr": "./qr/XTM-LHD-043.png"
  },
  {
    "codigo": "XTM-MANI-047",
    "equipo": "MANIPULADOR TELESCOPICO",
    "tipo": "Manipulador",
    "modelo": "JCB 533-105 T",
    "marca": "JCB",
    "estado": "Certificado",
    "tipo_certificado": "Ergonomia/FOPS/ROPS",
    "rig": "3465047",
    "serie": "JCB5AH2GTR3465047",
    "certificado_pdf": "./certificados/XTM-MANI-047_MANIPULADOR_ERGONOMIA-FOPS-ROPS.pdf",
    "validacion": "./validar.html?id=XTM-MANI-047",
    "qr": "./qr/XTM-MANI-047.png"
  },
  {
    "codigo": "XTM-MANI-869",
    "equipo": "MANIPULADOR TELESCOPICO",
    "tipo": "Manipulador",
    "modelo": "JCB 533-105 T",
    "marca": "JCB",
    "estado": "Certificado",
    "tipo_certificado": "Ergonomia/FOPS/ROPS",
    "rig": "3464869",
    "serie": "JCB5AH2GKR3464869",
    "certificado_pdf": "./certificados/XTM-MANI-869_MANIPULADOR_ERGONOMIA-FOPS-ROPS.pdf",
    "validacion": "./validar.html?id=XTM-MANI-869",
    "qr": "./qr/XTM-MANI-869.png"
  },
  {
    "codigo": "XTM-MANI-160",
    "equipo": "MANIPULADOR TELESCOPICO",
    "tipo": "Manipulador",
    "modelo": "JCB 533-105 T",
    "marca": "JCB",
    "estado": "Certificado",
    "tipo_certificado": "Ergonomia/FOPS/ROPS",
    "rig": "3465160",
    "serie": "JCB5AH2GER3465160",
    "certificado_pdf": "./certificados/XTM-MANI-160_MANIPULADOR_ERGONOMIA-FOPS-ROPS.pdf",
    "validacion": "./validar.html?id=XTM-MANI-160",
    "qr": "./qr/XTM-MANI-160.png"
  },
  {
    "codigo": "XTM-MANI-933",
    "equipo": "MANIPULADOR TELESCOPICO",
    "tipo": "Manipulador",
    "modelo": "JCB 533-105 T",
    "marca": "JCB",
    "estado": "Certificado",
    "tipo_certificado": "Ergonomia/FOPS/ROPS",
    "rig": "3464933",
    "serie": "JCB5AH2GCR3464933",
    "certificado_pdf": "./certificados/XTM-MANI-933_MANIPULADOR_ERGONOMIA-FOPS-ROPS.pdf",
    "validacion": "./validar.html?id=XTM-MANI-933",
    "qr": "./qr/XTM-MANI-933.png"
  },
  {
    "codigo": "XTM-MANI-747",
    "equipo": "MANIPULADOR TELESCOPICO",
    "tipo": "Manipulador",
    "modelo": "JCB 533-105 T",
    "marca": "JCB",
    "estado": "Certificado",
    "tipo_certificado": "Ergonomia/FOPS/ROPS",
    "rig": "3466747",
    "serie": "JCB5AH2GTR3466747",
    "certificado_pdf": "./certificados/XTM-MANI-747_MANIPULADOR_ERGONOMIA-FOPS-ROPS.pdf",
    "validacion": "./validar.html?id=XTM-MANI-747",
    "qr": "./qr/XTM-MANI-747.png"
  },
  {
    "codigo": "XTM-MANI-336",
    "equipo": "MANIPULADOR TELESCOPICO",
    "tipo": "Manipulador",
    "modelo": "JCB 533-105 T",
    "marca": "JCB",
    "estado": "Certificado",
    "tipo_certificado": "Ergonomia/FOPS/ROPS",
    "rig": "3465336",
    "serie": "JCB5AH2GER3465336",
    "certificado_pdf": "./certificados/XTM-MANI-336_MANIPULADOR_ERGONOMIA-FOPS-ROPS.pdf",
    "validacion": "./validar.html?id=XTM-MANI-336",
    "qr": "./qr/XTM-MANI-336.png"
  },
  {
    "codigo": "XTM-MANI-319",
    "equipo": "MANIPULADOR TELESCOPICO",
    "tipo": "Manipulador",
    "modelo": "JCB 533-105 T",
    "marca": "JCB",
    "estado": "Certificado",
    "tipo_certificado": "Ergonomia/FOPS/ROPS",
    "rig": "3465319",
    "serie": "JCB5AH2GER3465319",
    "certificado_pdf": "./certificados/XTM-MANI-319_MANIPULADOR_ERGONOMIA-FOPS-ROPS.pdf",
    "validacion": "./validar.html?id=XTM-MANI-319",
    "qr": "./qr/XTM-MANI-319.png"
  },
  {
    "codigo": "XTM-MANI-474",
    "equipo": "MANIPULADOR TELESCOPICO",
    "tipo": "Manipulador",
    "modelo": "JCB 533-105 T",
    "marca": "JCB",
    "estado": "Certificado",
    "tipo_certificado": "Ergonomia/FOPS/ROPS",
    "rig": "3465474",
    "serie": "JCB5AH2GCR3465474",
    "certificado_pdf": "./certificados/XTM-MANI-474_MANIPULADOR_ERGONOMIA-FOPS-ROPS.pdf",
    "validacion": "./validar.html?id=XTM-MANI-474",
    "qr": "./qr/XTM-MANI-474.png"
  },
  {
    "codigo": "XTM-MANI-512",
    "equipo": "MANIPULADOR TELESCOPICO",
    "tipo": "Manipulador",
    "modelo": "JCB 533-105 T",
    "marca": "JCB",
    "estado": "Pendiente",
    "tipo_certificado": "Sin certificado adjunto",
    "rig": "",
    "serie": "",
    "certificado_pdf": "",
    "validacion": "./validar.html?id=XTM-MANI-512",
    "qr": ""
  },
  {
    "codigo": "XTM-MANI-757",
    "equipo": "MANIPULADOR TELESCOPICO",
    "tipo": "Manipulador",
    "modelo": "JCB 533-105 T",
    "marca": "JCB",
    "estado": "Pendiente",
    "tipo_certificado": "Sin certificado adjunto",
    "rig": "",
    "serie": "",
    "certificado_pdf": "",
    "validacion": "./validar.html?id=XTM-MANI-757",
    "qr": ""
  },
  {
    "codigo": "XTM-MANI-891",
    "equipo": "MANIPULADOR TELESCOPICO",
    "tipo": "Manipulador",
    "modelo": "JCB 533-105 T",
    "marca": "JCB",
    "estado": "Pendiente",
    "tipo_certificado": "Sin certificado adjunto",
    "rig": "",
    "serie": "",
    "certificado_pdf": "",
    "validacion": "./validar.html?id=XTM-MANI-891",
    "qr": ""
  },
  {
    "codigo": "XTM-MANI-660",
    "equipo": "MANIPULADOR TELESCOPICO",
    "tipo": "Manipulador",
    "modelo": "JCB 533-105 T",
    "marca": "JCB",
    "estado": "Pendiente",
    "tipo_certificado": "Sin certificado adjunto",
    "rig": "",
    "serie": "",
    "certificado_pdf": "",
    "validacion": "./validar.html?id=XTM-MANI-660",
    "qr": ""
  },
  {
    "codigo": "XTM-RETRO-264",
    "equipo": "RETROEXCAVADORA",
    "tipo": "Retroexcavadora",
    "modelo": "JCB 3CX ECO",
    "marca": "JCB",
    "estado": "Certificado",
    "tipo_certificado": "Ergonomia/FOPS/ROPS",
    "rig": "3326264",
    "serie": "JCB3CX4TER3326264",
    "certificado_pdf": "./certificados/XTM-RETRO-264_RETROEXCAVADORA_ERGONOMIA-FOPS-ROPS.pdf",
    "validacion": "./validar.html?id=XTM-RETRO-264",
    "qr": "./qr/XTM-RETRO-264.png"
  },
  {
    "codigo": "XTM-RETRO-385",
    "equipo": "RETROEXCAVADORA",
    "tipo": "Retroexcavadora",
    "modelo": "JCB 3CX ECO",
    "marca": "JCB",
    "estado": "Certificado",
    "tipo_certificado": "Ergonomia/FOPS/ROPS",
    "rig": "3439385",
    "serie": "JCB3CX4TLR3439385",
    "certificado_pdf": "./certificados/XTM-RETRO-385_RETROEXCAVADORA_ERGONOMIA-FOPS-ROPS.pdf",
    "validacion": "./validar.html?id=XTM-RETRO-385",
    "qr": "./qr/XTM-RETRO-385.png"
  },
  {
    "codigo": "XTM-ROBOSHOT-231",
    "equipo": "ROBOSHOT ALPHA 30",
    "tipo": "Roboshot",
    "modelo": "Normet Alpha 30",
    "marca": "Normet",
    "estado": "Certificado",
    "tipo_certificado": "Cabina FOPS/ROPS",
    "rig": "EQA0231",
    "serie": "EQA0231",
    "certificado_pdf": "./certificados/XTM-ROBOSHOT-231_ROBOSHOT-ALPHA-30_CERT-CABINA.pdf",
    "validacion": "./validar.html?id=XTM-ROBOSHOT-231",
    "qr": "./qr/XTM-ROBOSHOT-231.png"
  },
  {
    "codigo": "XTM-ROBOSHOT-048",
    "equipo": "ROBOSHOT ALPHA 20",
    "tipo": "Roboshot",
    "modelo": "Normet Alpha 20",
    "marca": "Normet",
    "estado": "Certificado",
    "tipo_certificado": "Cabina FOPS/ROPS",
    "rig": "ELA1048",
    "serie": "ELA1048",
    "certificado_pdf": "./certificados/XTM-ROBOSHOT-048_ROBOSHOT-ALPHA-20_CERT-CABINA.pdf",
    "validacion": "./validar.html?id=XTM-ROBOSHOT-048",
    "qr": "./qr/XTM-ROBOSHOT-048.png"
  },
  {
    "codigo": "XTM-BOMBA-978",
    "equipo": "BOMBA DE HORMIGON TK 1004",
    "tipo": "Bomba",
    "modelo": "Bomba de Hormigon TK 1004",
    "marca": "",
    "estado": "Pendiente",
    "tipo_certificado": "Sin certificado adjunto",
    "rig": "",
    "serie": "",
    "certificado_pdf": "",
    "validacion": "./validar.html?id=XTM-BOMBA-978",
    "qr": ""
  },
  {
    "codigo": "XTM-MIX-132",
    "equipo": "MIXER",
    "tipo": "Mixer",
    "modelo": "Mixer",
    "marca": "",
    "estado": "Pendiente",
    "tipo_certificado": "Sin certificado adjunto",
    "rig": "",
    "serie": "",
    "certificado_pdf": "",
    "validacion": "./validar.html?id=XTM-MIX-132",
    "qr": ""
  },
  {
    "codigo": "XTM-MIX-152",
    "equipo": "MIXER",
    "tipo": "Mixer",
    "modelo": "Mixer",
    "marca": "",
    "estado": "Pendiente",
    "tipo_certificado": "Sin certificado adjunto",
    "rig": "",
    "serie": "",
    "certificado_pdf": "",
    "validacion": "./validar.html?id=XTM-MIX-152",
    "qr": ""
  },
  {
    "codigo": "XTM-ACUNADOR-427",
    "equipo": "ACUÑADOR SCALEMIN HT",
    "tipo": "Acuñador",
    "modelo": "Scalemin HT",
    "marca": "Resemin",
    "estado": "Certificado",
    "tipo_certificado": "FOPS/ROPS inspeccion BV",
    "rig": "JMC-1427",
    "serie": "JMC-1427",
    "certificado_pdf": "./certificados/XTM-ACUNADOR-427_SCALEMIN-HT_FOPS-ROPS.pdf",
    "validacion": "./validar.html?id=XTM-ACUNADOR-427",
    "qr": "./qr/XTM-ACUNADOR-427.png"
  }
];
